"""
Application-wide constants for the Collections Intelligence Agent.
"""

# --- Customer Segments ---
SEGMENT_SELF_CURE = "Self-Cure"
SEGMENT_MEDIUM_RISK = "Medium Risk"
SEGMENT_HIGH_RISK = "High Risk"

CUSTOMER_SEGMENTS = [SEGMENT_SELF_CURE, SEGMENT_MEDIUM_RISK, SEGMENT_HIGH_RISK]

# --- Recommended Actions ---
ACTION_REMINDER = "Send Reminder"
ACTION_RESTRUCTURE = "Offer EMI Restructure"
ACTION_SETTLEMENT = "Propose Settlement"
ACTION_ESCALATE = "Escalate to Recovery"

RECOMMENDED_ACTIONS = [ACTION_REMINDER, ACTION_RESTRUCTURE, ACTION_SETTLEMENT, ACTION_ESCALATE]

# --- Loan Types ---
LOAN_TYPE_PERSONAL = "Personal"
LOAN_TYPE_HOME = "Home"
LOAN_TYPE_AUTO = "Auto"
LOAN_TYPE_EDUCATION = "Education"

LOAN_TYPES = [LOAN_TYPE_PERSONAL, LOAN_TYPE_HOME, LOAN_TYPE_AUTO, LOAN_TYPE_EDUCATION]

# --- Employment Types ---
EMPLOYMENT_SALARIED = "Salaried"
EMPLOYMENT_SELF_EMPLOYED = "Self-Employed"

EMPLOYMENT_TYPES = [EMPLOYMENT_SALARIED, EMPLOYMENT_SELF_EMPLOYED]

# --- Interaction Types ---
INTERACTION_VOICE = "Voice"
INTERACTION_SMS = "SMS"
INTERACTION_CHAT = "Chat"
INTERACTION_EMAIL = "Email"

INTERACTION_TYPES = [INTERACTION_VOICE, INTERACTION_SMS, INTERACTION_CHAT, INTERACTION_EMAIL]

# --- Interaction Outcomes ---
OUTCOME_PROMISE_TO_PAY = "Promise to Pay"
OUTCOME_REFUSAL = "Refusal"
OUTCOME_NO_RESPONSE = "No Response"
OUTCOME_PARTIAL_PAYMENT = "Partial Payment"
OUTCOME_RESTRUCTURE_AGREED = "Restructure Agreed"

INTERACTION_OUTCOMES = [
    OUTCOME_PROMISE_TO_PAY, OUTCOME_REFUSAL, OUTCOME_NO_RESPONSE,
    OUTCOME_PARTIAL_PAYMENT, OUTCOME_RESTRUCTURE_AGREED
]

# --- Payment Methods ---
PAYMENT_UPI = "UPI"
PAYMENT_NEFT = "NEFT"
PAYMENT_AUTO_DEBIT = "Auto-Debit"
PAYMENT_CASH = "Cash"
PAYMENT_CHEQUE = "Cheque"

PAYMENT_METHODS = [PAYMENT_UPI, PAYMENT_NEFT, PAYMENT_AUTO_DEBIT, PAYMENT_CASH, PAYMENT_CHEQUE]

# --- Supported Languages ---
LANG_ENGLISH = "English"
LANG_HINDI = "Hindi"
LANG_TAMIL = "Tamil"
LANG_TELUGU = "Telugu"
LANG_MARATHI = "Marathi"
LANG_KANNADA = "Kannada"

SUPPORTED_LANGUAGES = [LANG_ENGLISH, LANG_HINDI, LANG_TAMIL, LANG_TELUGU, LANG_MARATHI, LANG_KANNADA]

# --- Risk Thresholds (used in analytics) ---
DAYS_PAST_DUE_LOW = 0        # On-time
DAYS_PAST_DUE_MEDIUM = 15    # Early warning
DAYS_PAST_DUE_HIGH = 30      # Pre-delinquent
DAYS_PAST_DUE_CRITICAL = 60  # Delinquent

SELF_CURE_THRESHOLD_HIGH = 0.7    # Above = likely self-cure
SELF_CURE_THRESHOLD_MEDIUM = 0.4  # 0.4 - 0.7 = medium risk
# Below 0.4 = high risk
